name: MacOS

on:
  pull_request:
    branches-ignore: dev

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: ./ci_scripts/ci_macos_deps.sh  
      - name: Build
        run: ./ci_scripts/ci_macos_build.sh  
      - name: Test
        run: ./ci_scripts/ci_macos_test.sh  
        
